[package]
name = "zyvor-janus-scheduler"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "Zyvor Janus scheduling policies"

[dependencies]
zyvor-janus-core = { path = "../zyvor-janus-core" }
zyvor-janus-model = { path = "../zyvor-janus-model" }
zyvor-janus-topology = { path = "../zyvor-janus-topology" }
