[package]
name = "zyvor-janus-py"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "Python bindings for Zyvor Janus"

[lib]
name = "zyvor_janus"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { workspace = true }
zyvor-janus-core = { path = "../zyvor-janus-core" }
zyvor-janus-config = { path = "../zyvor-janus-config" }
zyvor-janus-metrics = { path = "../zyvor-janus-metrics" }
